//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelTracking.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permit
    {
        public int id { get; set; }
        public System.DateTime startingdate { get; set; }
        public System.DateTime duedate { get; set; }
        public int personnel_id { get; set; }
    
        public virtual Personnel Personnel { get; set; }
    }
}
