//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonnelTracking.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personnel
    {
        public Personnel()
        {
            this.Permits = new HashSet<Permit>();
        }
    
        public int id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string phonenumber { get; set; }
        public string address { get; set; }
        public int totalpermit { get; set; }
        public int usedpermit { get; set; }
    
        public virtual ICollection<Permit> Permits { get; set; }
    }
}
